version: "3"
services: 
  api:
    build: .
    image: whatsapp-bot:latest
    command: yarn bot
    container_name: whatsapp-bot2
    volumes:
      - .:/usr/whatsapp-bot
    environment:
      - BROWSER_ID="OW/9ml9pRFByEpQbnsVAiw=="
      - SECRET_BUNDLE={"key":"hdMEqn0EFHawrD6jG+/r3lye22AyzsLqwutsVyc1Ul8=","encKey":"jypuiEtlXJ9wKirqdWca2tRG7YZLZq6WLemCduVFwuQ=","macKey":"hdMEqn0EFHawrD6jG+/r3lye22AyzsLqwutsVyc1Ul8="}
      - TOKEN1="gio7O+V4Ppa/SAHp7ogER9hBBkv3XMNvBAw2gJJc8jQ="
      - TOKEN2="1@EKBqC2QvHqehb4KYjCwsmojRg+dReQHJlW4Qv08qpIBisCa4FAE7kh+MzaTydkNRjVdcKGgjWRiz4A=="
      - NO_SANDBOX=true