version: "3"
services: 
  api:
    build: .
    image: whatsapp-bot:latest
    command: yarn bot
    container_name: whatsapp-bot2
    volumes:
      - .:/usr/whatsapp-bot
    environment:
      - BROWSER_ID="yKBP1DEuf1iZbwrsOzP0iQ=="
      - SECRET_BUNDLE={"key":"l7pvbcdR7NUHu63Gjn7J4qoJonRJB9Axv5SZ5NkE+no=","encKey":"sajxFmu+soJGDkjKZQaYt5GdyVxaEcjV/+ydOGqqVVA=","macKey":"l7pvbcdR7NUHu63Gjn7J4qoJonRJB9Axv5SZ5NkE+no="}
      - TOKEN1="rVFBPkrVWikdALRG6KgVwctEJfGB0J/4H8zbEwkDAR8="
      - TOKEN2="1@3d8l8wPqbut5DeQG1ZeEtmaRPZviRRPdKeNOZEI+Rf9SU5dNpo2RlY/kpybMfgg564PQc++fzmyYyw=="