version: "3"
services: 
  api:
    build: .
    image: whatsapp-bot:latest
    command: yarn bot
    container_name: whatsapp-bot2
    volumes:
      - .:/usr/whatsapp-bot
    environment:
      - BROWSER_ID="GyVoRsChqy6kZqWetSnViQ=="
      - SECRET_BUNDLE={"key":"PwFJaseNyEqlpvZpXD/rHOGoDtbUoqdhZVbc485X3c4=","encKey":"HNxgo5ZkTWkmY4axBaP1ABePG8dWLgSRuv0faCL9Wno=","macKey":"PwFJaseNyEqlpvZpXD/rHOGoDtbUoqdhZVbc485X3c4="}
      - TOKEN1="wta08e4IMWBXey/oCuqD5NgMcua4OrS7yRRLEwOs/7w="
      - TOKEN2="1@yzRcFMOIzyyqAfhW+J+r+9ISyLx+VYhfkujJ4+qWkY00Oh1/4Vng29fq0V6TCPPdUy/djAxuwm9tEw=="